pipeline {
    agent any

    environment {
        IMAGE_NAME = 'sameedshoaib1/banking-api'
        IMAGE_TAG = '1.0.2'
        REPO_URL = 'https://github.com/sameedshoaibb/devops-web-api.git'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "cd banking-api"
                sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
            }
        }

        stage('Test Health Endpoint') {
            steps {
                sh "docker run -d --name banking-api-test -p 4000:4000 ${IMAGE_NAME}:${IMAGE_TAG}"
                sh "sleep 5"
                sh "curl -f http://localhost:4000/health"
                sh "docker stop banking-api-test && docker rm banking-api-test"
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh "echo ${DOCKER_PASS} | docker login -u ${DOCKER_USER} --password-stdin"
                    sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    def env = env.BRANCH_NAME == 'main' ? 'prod' : 'dev'
                    sh "./scripts/deploy/deploy.sh ${env}"
                }
            }
        }
    }

    post {
        always {
            sh 'docker rmi sameedshoaib1/banking-api || true'
        }
    }
}
