pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    environment {
        IMAGE_NAME = 'sameedshoaib1/banking-api'
        IMAGE_TAG = 'v1.0.2'
        REPO_URL = 'https://github.com/sameedshoaibb/devops-web-api.git'
    }

    stages {
        stage('Clean Workspace') {
            steps {
                cleanWs()
            }
        }

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "pwd"
                sh "ls -al"
                sh "ls -al banking-api || echo 'banking-api folder not found'"
                sh "cat banking-api/Dockerfile || echo 'Dockerfile not found'"
                dir('banking-api') {
                    sh "pwd"
                    sh "ls -al"
                    sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
                }
            }
        }

        stage('Test Health Endpoint') {
            steps {
                sh "docker rm -f banking-api-test || true"
                sh "docker run -d --name banking-api-test -p 4000:4000 ${IMAGE_NAME}:${IMAGE_TAG}"
                sh "sleep 5"
                sh "curl -f http://localhost:4000/health"
                sh "docker stop banking-api-test && docker rm banking-api-test"
            }
        }

        stage('Push to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                    sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('banking-api') {
                    sh "./scripts/deploy/deploy.sh prod"
                }
            }
        }

        stage('Verify Deployment') {
            steps {
                                sh "kubectl get all -n banking-api"
                                sh "kubectl get endpoints -n banking-api"
                                sh "kubectl get pods -n banking-api -o wide"
            }
        }
    }

    post {
        always {
            sh "docker rmi ${IMAGE_NAME}:${IMAGE_TAG} || true"
            sh "docker rm -f banking-api-test || true"
        }
    }
}
