# ArgoCD Application with resource tracking for values.prod.yaml only
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-api-prod-values-only
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # This annotation tells ArgoCD to only sync when specific files change
    argocd.argoproj.io/manifest-generate-paths: "banking-api/helm/values.prod.yaml"
spec:
  project: default
  source:
    repoURL: https://github.com/sameedshoaibb/devops-web-api.git
    targetRevision: main
    path: banking-api/helm
    helm:
      valueFiles:
        - values.yaml
        - values.prod.yaml
      parameters:
        - name: app.imageTag
          value: "v1.0.2"
  destination:
    server: https://kubernetes.default.svc
    namespace: banking-api-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
  # Configure refresh settings to check for changes more frequently
  info:
    - name: "Monitoring"
      value: "values.prod.yaml file changes only"
  revisionHistoryLimit: 10
---
# AppProject with specific source restrictions
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: values-only-monitoring
  namespace: argocd
spec:
  description: Project for monitoring specific values files
  sourceRepos:
    - 'https://github.com/sameedshoaibb/devops-web-api.git'
  destinations:
    - namespace: 'banking-api-*'
      server: https://kubernetes.default.svc
    - namespace: 'argocd'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: 'apps'
      kind: Deployment
    - group: ''
      kind: Service
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
  roles:
    - name: values-watcher
      description: Role for watching values files
      policies:
        - p, proj:values-only-monitoring:values-watcher, applications, get, values-only-monitoring/*, allow
        - p, proj:values-only-monitoring:values-watcher, applications, sync, values-only-monitoring/*, allow